# ========================
# BASE DE DATOS (Clever Cloud)
# ========================
spring.datasource.url=jdbc:mysql://bfdhqzrw2tclchmwzuid-mysql.services.clever-cloud.com:3306/bfdhqzrw2tclchmwzuid?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&autoReconnect=true&maxReconnects=3
spring.datasource.username=ug9aqzkcpc8lsj2z
spring.datasource.password=D9pHlS4b8NyYybzmvlls

# ========================
# HIKARI (CONTROL DE CONEXIONES)
# ========================
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.keepalive-time=30000

# IMPORTANTE (evita fallos en Render)
spring.datasource.hikari.initialization-fail-timeout=0

# ========================
# JPA / HIBERNATE
# ========================
spring.jpa.hibernate.ddl-auto=none

# Encoding
spring.jpa.properties.hibernate.connection.characterEncoding=utf8mb4
spring.jpa.properties.hibernate.connection.useUnicode=true

# ========================
# MAIL (GMAIL)
# ========================
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=geotradeconoce@gmail.com
spring.mail.password=ehrsjnvoabvgiiwf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.properties.mail.smtp.ssl.enable=true


cloudinary.cloud_name=davhngrmh
cloudinary.api_key=591478428319619
cloudinary.api_secret=wVmOpTKqHjSHFWYejbyxU2Ln4dk

spring.main.allow-bean-definition-overriding=true